name: FEROX

on:
    workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Setup golang
        uses: actions/setup-go@v2
        #with:
          #go-version: 1.18
          #cache: 'go'
          #path: /home/runner/go
          #key: ${{ runner.os }}-go

      - name: Setup Dependencies
        run: |
          #nohup --version
          sudo apt-get update
          #sudo apt-get install libpcap-dev
          #rm -rf test.html
          curl -sL https://raw.githubusercontent.com/epi052/feroxbuster/master/install-nix.sh | bash &
          feroxbuster --help

      - name: Running Scanner
        run: |
          #cat urls.txt
          #for i in $(cat urls.txt); do katana -u $i -cs ${i#*//} -aff -H -jc -d 7 -proxy http://127.0.0.1:7777; done
          for i in $(cat urls.txt); do feroxbuster -u $i -w mid.txt | tee result.txt
          #katana -u "http://testasp.vulnweb.com" -aff -H -jc -d 7 
          cat test.html
        shell: bash

      - name: Sorting the output results
        run: |
          find result.txt -type f -exec sort {} -o {} \;
        shell: bash

      - name: Create local changes
        run: |
          git add result.txt
      - name: Commit results to Github
        run: |
          git config --local user.email "jinbao1986@qq.com"
          git config --global user.name "TNT"
          git commit -m "InCloud Report" -a --allow-empty
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
